<?php

function GenerateSiteConfig($host, $dir) {
	$ret =
"# Config generated by Yuuki Stats Tracker
server {
	listen 80;
	
	root ". $dir .";
	index index.html index.htm index.php;

	server_name ". $host .";

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files \$uri =404;
	}

	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/var/run/php5-fpm.sock;
		fastcgi_index index.php;
		include fastcgi_params;
	}
	
    location /publish {
        rewrite ^/publish/([^/]+)a /legacy.php?data=$1;
    }

	error_page 404 /404.html;
}";

	return $ret;
}

?>