# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('fingerprint', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('port', models.PositiveIntegerField()),
                ('tshock_version', models.CharField(max_length=20)),
                ('terraria_version', models.CharField(max_length=20)),
                ('is_legacy', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server')),
            ],
        ),
        migrations.CreateModel(
            name='ServerProvider',
            fields=[
                ('provider_token', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('color_normal', models.CharField(max_length=7)),
                ('color_highlight', models.CharField(max_length=7)),
                ('is_official', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_players', models.PositiveIntegerField()),
                ('max_players', models.PositiveIntegerField()),
                ('memory', models.BigIntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Server')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ServerProvider'),
        ),
    ]
