# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170615_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverstats',
            options={'ordering': ('added_at',)},
        ),
        migrations.AddField(
            model_name='serverstats',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
